name: Workflows

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    Tests:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install node
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm install

            - name: Lint
              run: npm run lint

            - name: Format check
              run: npm run format -- --check

            - name: Execute test suite
              run: npm test
              